import { Providers } from './providers';

/**
 * The metadata for the app.
 */
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

/**
 * The root layout for the web app.
 * @param children The children to render.
 * @returns The root layout.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
