export const amexRewards = {
  used: [
    {
      status: 'used',
      rewardType: 'annual',
      title: 'Airline Fee Credit',
      description: 'For incidental fees like baggage or seat selection on one qualifying airline.',
      estimatedValue: '$200',
      activation: 'Select one qualifying airline on Amex website.',
      conditions: 'Fees must be charged by the selected airline.',
      statusIcon: 'check-circle',
      statusColor: '#2ECC71',
    },
    {
      status: 'used',
      rewardType: 'annual',
      title: 'Hotel Credit',
      description: 'For prepaid bookings through Fine Hotels + Resorts or The Hotel Collection.',
      estimatedValue: '$200',
      activation: 'Book through Fine Hotels + Resorts or The Hotel Collection.',
      conditions: 'Minimum two-night stay for The Hotel Collection.',
      statusIcon: 'check-circle',
      statusColor: '#2ECC71',
    },
    {
      status: 'used',
      rewardType: 'annual',
      title: 'Equinox Credit',
      description: 'For eligible Equinox memberships or the Equinox+ app.',
      estimatedValue: '$300',
      activation: 'Pay for Equinox with your card.',
      conditions: 'Valid for eligible Equinox memberships.',
      statusIcon: 'check-circle',
      statusColor: '#2ECC71',
    },
    {
      status: 'used',
      rewardType: 'annual',
      title: 'CLEAR Plus Credit',
      description: 'For the annual membership fee for CLEAR Plus.',
      estimatedValue: '$189',
      activation: 'Pay for CLEAR Plus with your card.',
      conditions: "Membership is subject to CLEAR's terms.",
      statusIcon: 'check-circle',
      statusColor: '#2ECC71',
    },
    {
      status: 'used',
      rewardType: 'oneTime',
      title: 'Welcome Bonus',
      description: 'Earn 100,000 Membership Rewards Points after you spend $6,000 on purchases on your new Card in your first 6 months of Card Membership.',
      estimatedValue: '$1000',
      activation: 'Meet spending threshold.',
      conditions: 'Offer may not be available to all applicants.',
      statusIcon: 'check-circle',
      statusColor: '#2ECC71',
    },
  ],
  inProgress: [
    {
      status: 'inProgress',
      rewardType: 'semiannual',
      title: 'Saks Fifth Avenue Credit',
      description: 'Provided as two $50 credits; one for January-June and one for July-December.',
      estimatedValue: '$100',
      activation: 'Enrollment required.',
      conditions: 'Valid for purchases at Saks Fifth Avenue.',
      statusIcon: 'spinner',
      statusColor: '#F1C40F',
    },
    {
      status: 'inProgress',
      rewardType: 'monthly',
      title: 'Digital Entertainment Credit',
      description: 'Provided as up to $20 in monthly credits for eligible streaming and digital services.',
      estimatedValue: '$240',
      activation: 'Enrollment required.',
      conditions: 'Valid for participating partners only.',
      statusIcon: 'spinner',
      statusColor: '#F1C40F',
    },
    {
      status: 'inProgress',
      rewardType: 'monthly',
      title: 'Uber Cash',
      description: 'Provided as $15 in Uber Cash each month, with a $20 bonus in December.',
      estimatedValue: '$200',
      activation: 'Add your card to your Uber account.',
      conditions: 'For U.S. rides and eats.',
      statusIcon: 'spinner',
      statusColor: '#F1C40F',
    },
    {
      status: 'inProgress',
      rewardType: 'monthly',
      title: 'Walmart+ Monthly Membership Credit',
      description: 'Covers the monthly cost of a Walmart+ membership.',
      estimatedValue: '$155',
      activation: 'Pay for Walmart+ with your card.',
      conditions: 'Excludes any other subscription plans.',
      statusIcon: 'spinner',
      statusColor: '#F1C40F',
    },
    {
      status: 'inProgress',
      rewardType: 'quarterly',
      title: 'Quarterly Credit',
      description: 'Get $50 back in statement credits each quarter.',
      estimatedValue: '$200',
      activation: 'Enrollment required.',
      conditions: 'Valid for participating partners only.',
      statusIcon: 'spinner',
      statusColor: '#F1C40F',
    },
  ],
  unused: [
    {
      status: 'unused',
      rewardType: 'multiYear',
      title: 'Global Entry or TSA PreCheck Credit',
      description: 'A statement credit for the application fee, available once every 4 to 4.5 years.',
      estimatedValue: '$100',
      activation: 'Apply and pay with your card.',
      conditions: 'Credit available once every 4-4.5 years.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Global Lounge Collection',
      description: 'Access to over 1,400 airport lounges worldwide.',
      estimatedValue: 'Varies',
      activation: 'Enrollment required for Priority Pass.',
      conditions: 'Varies by lounge program.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Premium Concierge Service',
      description: '24/7 assistance with travel, dining, and event planning.',
      estimatedValue: 'Varies',
      activation: 'Call the number on the back of your card.',
      conditions: 'Services are complimentary, but you pay for purchased items.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Marriott Bonvoy Gold Elite Status',
      description: 'Complimentary hotel status.',
      estimatedValue: 'Varies',
      activation: 'Enrollment required.',
      conditions: 'Benefits subject to availability.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Hilton Honors Gold Status',
      description: 'Complimentary hotel status.',
      estimatedValue: 'Varies',
      activation: 'Enrollment required.',
      conditions: 'Benefits vary by property.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Car Rental Privileged Status',
      description: 'Elite status with Avis, Hertz, and National.',
      estimatedValue: 'Varies',
      activation: 'Enrollment required.',
      conditions: 'Varies by rental company.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Fine Hotels + Resorts (FHR) Program Benefits',
      description: 'Perks like breakfast for two, room upgrades, and late checkout.',
      estimatedValue: 'Varies',
      activation: 'Book through Fine Hotels + Resorts.',
      conditions: 'Varies by property.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'The Hotel Collection Benefits',
      description: 'Room upgrades and experience credits on stays of 2+ nights.',
      estimatedValue: 'Varies',
      activation: 'Book through The Hotel Collection.',
      conditions: 'Minimum two-night stay.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Global Dining Access by Resy',
      description: 'Access to exclusive reservations and culinary events.',
      estimatedValue: 'Varies',
      activation: 'Add your card to your Resy profile.',
      conditions: 'Reservations subject to availability.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'International Airline Program',
      description: 'Savings on premium cabin international tickets.',
      estimatedValue: 'Varies',
      activation: 'Book through AmexTravel.com.',
      conditions: 'Varies by airline.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Membership Rewards Points',
      description: 'The core program for earning and redeeming points.',
      estimatedValue: 'Varies',
      activation: 'Automatic.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Amex Offers',
      description: 'Access to targeted discounts and bonus point offers.',
      estimatedValue: 'Varies',
      activation: 'Add offers to your card.',
      conditions: 'Varies by offer.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Cell Phone Protection',
      description: 'Insurance for your damaged or stolen cell phone.',
      estimatedValue: 'Varies',
      activation: 'Pay your cell phone bill with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Trip Delay Insurance',
      description: 'Insurance for trip delays.',
      estimatedValue: 'Varies',
      activation: 'Pay for your trip with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Trip Cancellation and Interruption Insurance',
      description: 'Insurance for trip cancellations and interruptions.',
      estimatedValue: 'Varies',
      activation: 'Pay for your trip with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Baggage Insurance Plan',
      description: 'Insurance for lost, stolen, or damaged baggage.',
      estimatedValue: 'Varies',
      activation: 'Pay for your trip with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Car Rental Loss and Damage Insurance',
      description: 'Insurance for rental car loss and damage.',
      estimatedValue: 'Varies',
      activation: 'Pay for your rental with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Purchase Protection',
      description: 'Protection for purchases.',
      estimatedValue: 'Varies',
      activation: 'Make a purchase with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Extended Warranty',
      description: 'Extended warranty for purchases.',
      estimatedValue: 'Varies',
      activation: 'Make a purchase with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'Return Protection',
      description: 'Return protection for purchases.',
      estimatedValue: 'Varies',
      activation: 'Make a purchase with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'No Foreign Transaction Fees',
      description: 'No foreign transaction fees.',
      estimatedValue: 'Varies',
      activation: 'Automatic.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
    {
      status: 'unused',
      rewardType: 'asNeeded',
      title: 'SoulCycle At-Home Bike Credit',
      description: 'A statement credit to be used when you purchase an eligible bike.',
      estimatedValue: '$300',
      activation: 'Pay for your SoulCycle bike with your card.',
      conditions: 'Terms and conditions apply.',
      statusIcon: 'times-circle',
      statusColor: '#E74C3C',
    },
  ],
};